version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: fs-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fs-admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: finances_summary
    ports:
      - 27017:27017
    networks:
      - fs
    volumes:
      - ./scripts/mongo-entrypoint-dev.js:/docker-entrypoint-initdb.d/mongo-entrypoint-dev.js:ro

  starlette:
    container_name: fs-starlette
    build:
      context: ./
      dockerfile: ./Starlette.Dockerfile
    ports:
      - 8000:8000
    networks:
      - fs
    volumes:
      - ./src/finances_summary:/finances_summary/
    depends_on:
      - mongo

  frontend:
    container_name: fs-frontend
    build:
      context: ./
      dockerfile: Frontend.Dockerfile
    ports: 
      - 3000:3000
    networks:
      - fs
    volumes:
      - ./src/frontend/src:/frontend/src
    depends_on:
      - starlette

networks:
  fs:
    driver: bridge