name: build

on: [push]
jobs:
  build-be:
    runs-on: ubuntu-latest
    
    steps:
    - name: Make envfile
      env:
        # MONGO
        MONGO_HOST: ${{secrets.MONGO_HOST}}
        MONGO_HOSTNAME: ${{secrets.MONGO_HOSTNAME}}
        MONGO_DATABASE: ${{secrets.MONGO_DATABASE}}
        MONGO_USERNAME: ${{secrets.MONGO_USERNAME}}
        MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
        # STARLETTE
        ALLOWED_ORIGINS: ${{secrets.ALLOWED_ORIGINS}}
        SESSION_MIDDLEWARE_SECRET: ${{secrets.SESSION_MIDDLEWARE_SECRET}}
        STARLETTE_HOST: ${{secrets.STARLETTE_HOST}}
        STARLETTE_PORT: ${{secrets.STARLETTE_PORT}}
        STARLETTE_RELOAD: ${{secrets.STARLETTE_RELOAD}}
        STARLETTE_SSL_KEYFILE: ${{secrets.STARLETTE_SSL_KEYFILE}}
        STARLETTE_SSL_CERTFILE: ${{secrets.STARLETTE_SSL_CERTFILE}}
        # API
        API_KEY_POLYGON: ${{secrets.API_KEY_POLYGON}}

    - uses: actions/checkout@v2
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    # - name: pip install
    #   run: pip install --requirement ./src/finances_summary/requirements.txt
    # - name: run api
    #   run: |
    #     export PYTHONPATH=${GITHUB_WORKSPACE}/src/
    #     cd src
    #     python ./finances_summary/app.py
    - name: Run docker app
      run: docker-compose --file docker-compose-dev.yaml up --build
  # build-fe:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '16'
  #   - name: install packages
  #     run: npm i
  #     working-directory: ./src/frontend
  #   - name: run build
  #     run: npm run build
  #     working-directory: ./src/frontend
  