name: build

on: [push]
jobs:
  # build-be:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v3
  #   - run: docker-compose --file docker-compose-dev.yaml up --build
  build-fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
      working-directory: ./src/frontend
    - run: ls -a
    - run: npm i
    - run: npm run build
  