name: build

on: [push]
jobs:
  build-be:
    runs-on: ubuntu-latest
    
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        # MONGO
        MONGO_HOST: 0.0.0.0
        MONGO_HOSTNAME: fs-mongo
        MONGO_DATABASE: finances_summary
        MONGO_USERNAME: fs-admin
        MONGO_PASSWORD: 123456
        # STARLETTE
        ALLOWED_ORIGINS: https://0.0.0.0:3000
        SESSION_MIDDLEWARE_SECRET: vWZvTiSGc2EkQqsdgeuaTHLa9Eu4s237J9MoLJ39nU2CSacajudrCNjRboSjcqjs
        STARLETTE_HOST: 0.0.0.0
        STARLETTE_PORT: 8000
        STARLETTE_RELOAD: true
        STARLETTE_SSL_KEYFILE: /finances_summary/secrets/0.0.0.0+2-key.pem
        STARLETTE_SSL_CERTFILE: /finances_summary/secrets/0.0.0.0+2.pem
        # API
        API_KEY_POLYGON: pNcuEhFrrTZESeXzsoMFQE1AwVuVk5S2
        # directory: ./
        file_name: .env
        fail_on_empty: true

    - uses: actions/checkout@v2
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    # - name: pip install
    #   run: pip install --requirement ./src/finances_summary/requirements.txt
    # - name: run api
    #   run: |
    #     export PYTHONPATH=${GITHUB_WORKSPACE}/src/
    #     cd src
    #     python ./finances_summary/app.py
    - name: Run docker app
      run: docker-compose --file docker-compose-dev.yaml up --build
  # build-fe:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '16'
  #   - name: install packages
  #     run: npm i
  #     working-directory: ./src/frontend
  #   - name: run build
  #     run: npm run build
  #     working-directory: ./src/frontend
  