name: tests

on: [push]
jobs:
  run_tests:
    needs: run_docker_app
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: Run python tests
      run: pytest src/finances_summary/tests/